/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID cadence8)
#  Generated on:      Thu Aug 14 12:11:08 2025
#  Design:            ALU
#  Command:           saveNetlist ALU_layout.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug  9 2025 15:11:54 IST (Aug  9 2025 09:41:54 UTC)
// Verification Directory fv/ALU 
module ALU (
	a, 
	b, 
	en, 
	opcode, 
	result);
   input a;
   input b;
   input en;
   input [3:0] opcode;
   output [31:0] result;

   // Internal wires
   wire FE_OFN5_result_27;
   wire FE_OFN3_result_25;
   wire FE_OFN2_result_16;
   wire FE_OFN1_result_23;
   wire FE_OFN0_n_80;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_46;
   wire n_47;
   wire n_50;
   wire n_51;
   wire n_56;
   wire n_79;
   wire n_80;

   CLKBUFX20 FE_OFC5_result_27 (.A(FE_OFN5_result_27),
	.Y(result[27]));
   CLKBUFX20 FE_OFC4_result_31 (.A(FE_OFN1_result_23),
	.Y(result[31]));
   CLKBUFX20 FE_OFC3_result_25 (.A(FE_OFN3_result_25),
	.Y(result[25]));
   CLKBUFX20 FE_OFC2_result_16 (.A(FE_OFN2_result_16),
	.Y(result[16]));
   CLKBUFX20 FE_OFC1_result_23 (.A(FE_OFN1_result_23),
	.Y(result[23]));
   CLKBUFX4 FE_OFC0_n_80 (.A(n_80),
	.Y(FE_OFN0_n_80));
   TBUFX20 g44__2398 (.A(n_56),
	.OE(en),
	.Y(result[0]));
   TBUFX20 g43__5107 (.A(n_51),
	.OE(en),
	.Y(result[1]));
   CLKINVX12 g1912 (.A(FE_OFN0_n_80),
	.Y(result[17]));
   CLKINVX12 g1909 (.A(FE_OFN0_n_80),
	.Y(result[29]));
   CLKINVX12 g1913 (.A(FE_OFN0_n_80),
	.Y(result[28]));
   CLKINVX1 g1914 (.A(n_80),
	.Y(FE_OFN1_result_23));
   CLKINVX12 g1910 (.A(FE_OFN0_n_80),
	.Y(result[19]));
   CLKINVX1 g1903 (.A(FE_OFN0_n_80),
	.Y(FE_OFN5_result_27));
   CLKINVX12 g1904 (.A(FE_OFN0_n_80),
	.Y(result[24]));
   CLKINVX12 g1908 (.A(FE_OFN0_n_80),
	.Y(result[20]));
   CLKINVX1 g1905 (.A(FE_OFN0_n_80),
	.Y(FE_OFN3_result_25));
   CLKINVX12 g1901 (.A(FE_OFN0_n_80),
	.Y(result[21]));
   CLKINVX12 g1902 (.A(FE_OFN0_n_80),
	.Y(result[22]));
   NAND3X1 g1898__6260 (.A(n_46),
	.B(n_23),
	.C(n_27),
	.Y(n_56));
   CLKINVX12 g1907 (.A(FE_OFN0_n_80),
	.Y(result[26]));
   CLKINVX12 g1900 (.A(FE_OFN0_n_80),
	.Y(result[30]));
   CLKINVX1 g1899 (.A(FE_OFN0_n_80),
	.Y(FE_OFN2_result_16));
   CLKINVX12 g1906 (.A(FE_OFN0_n_80),
	.Y(result[18]));
   NAND2XL g1915__8428 (.A(n_50),
	.B(n_33),
	.Y(n_51));
   TBUFX20 g32__5526 (.A(n_47),
	.OE(en),
	.Y(result[12]));
   TBUFX12 g36__6783 (.A(n_47),
	.OE(en),
	.Y(result[8]));
   AOI222XL g1919__3680 (.A0(n_28),
	.A1(n_21),
	.B0(a),
	.B1(n_32),
	.C0(n_12),
	.C1(n_11),
	.Y(n_46));
   TBUFX12 g29__1617 (.A(n_47),
	.OE(en),
	.Y(result[15]));
   TBUFX12 g30__2802 (.A(n_47),
	.OE(en),
	.Y(result[14]));
   TBUFX20 g31__1705 (.A(n_47),
	.OE(en),
	.Y(result[13]));
   TBUFX12 g40__5122 (.A(n_47),
	.OE(en),
	.Y(result[4]));
   TBUFX20 g38__8246 (.A(n_47),
	.OE(en),
	.Y(result[6]));
   TBUFX20 g34__7098 (.A(n_47),
	.OE(en),
	.Y(result[10]));
   TBUFX20 g35__6131 (.A(n_47),
	.OE(en),
	.Y(result[9]));
   TBUFX12 g37__1881 (.A(n_47),
	.OE(en),
	.Y(result[7]));
   TBUFX12 g33__5115 (.A(n_47),
	.OE(en),
	.Y(result[11]));
   TBUFX20 g39__7482 (.A(n_47),
	.OE(en),
	.Y(result[5]));
   TBUFX20 g42__4733 (.A(n_47),
	.OE(en),
	.Y(result[2]));
   TBUFX12 g41__6161 (.A(n_47),
	.OE(en),
	.Y(result[3]));
   INVXL g1917 (.A(n_47),
	.Y(n_50));
   OR2X4 g1918__9315 (.A(n_9),
	.B(n_31),
	.Y(n_47));
   AOI33XL g1922__9945 (.A0(n_30),
	.A1(b),
	.A2(n_20),
	.B0(opcode[0]),
	.B1(n_29),
	.B2(n_6),
	.Y(n_33));
   AOI21XL g1924__2883 (.A0(opcode[1]),
	.A1(n_13),
	.B0(n_26),
	.Y(n_32));
   OAI32XL g1920__2346 (.A0(n_30),
	.A1(n_29),
	.A2(n_19),
	.B0(n_25),
	.B1(opcode[1]),
	.Y(n_31));
   OAI211XL g1921__1666 (.A0(n_15),
	.A1(n_79),
	.B0(n_18),
	.C0(n_17),
	.Y(n_28));
   NAND2XL g1923__7410 (.A(n_16),
	.B(n_3),
	.Y(n_27));
   NOR2XL g1926__6417 (.A(n_14),
	.B(n_22),
	.Y(n_26));
   OA21X1 g1925__5477 (.A0(n_29),
	.A1(n_79),
	.B0(n_23),
	.Y(n_25));
   MXI2XL g1932__2398 (.A(n_79),
	.B(n_5),
	.S0(n_21),
	.Y(n_22));
   MXI2XL g1933__5107 (.A(n_10),
	.B(n_19),
	.S0(n_29),
	.Y(n_20));
   OAI211XL g1929__6260 (.A0(n_2),
	.A1(a),
	.B0(opcode[2]),
	.C0(n_7),
	.Y(n_18));
   NAND4XL g1928__4319 (.A(n_19),
	.B(opcode[1]),
	.C(n_4),
	.D(n_29),
	.Y(n_17));
   OAI32XL g1930__8428 (.A0(opcode[2]),
	.A1(n_21),
	.A2(n_15),
	.B0(n_29),
	.B1(a),
	.Y(n_16));
   AOI211XL g1931__5526 (.A0(opcode[3]),
	.A1(n_8),
	.B0(n_29),
	.C0(n_13),
	.Y(n_14));
   NAND2XL g1934__6783 (.A(n_79),
	.B(opcode[1]),
	.Y(n_12));
   NAND3XL g1927__3680 (.A(n_11),
	.B(opcode[0]),
	.C(n_10),
	.Y(n_23));
   NOR3XL g1935__1617 (.A(n_10),
	.B(n_8),
	.C(opcode[2]),
	.Y(n_9));
   OAI2BB1XL g1936__2802 (.A0N(opcode[0]),
	.A1N(opcode[3]),
	.B0(a),
	.Y(n_7));
   INVXL g1938 (.A(n_15),
	.Y(n_6));
   NOR3XL g1937__1705 (.A(n_21),
	.B(a),
	.C(opcode[2]),
	.Y(n_11));
   NOR2XL g1943__5122 (.A(opcode[0]),
	.B(n_29),
	.Y(n_5));
   NOR2XL g1944__8246 (.A(n_4),
	.B(opcode[1]),
	.Y(n_30));
   INVXL g1942 (.A(n_3),
	.Y(n_19));
   NOR2XL g1939__6131 (.A(opcode[0]),
	.B(opcode[1]),
	.Y(n_2));
   NAND2XL g1941__1881 (.A(opcode[1]),
	.B(a),
	.Y(n_15));
   NOR2XL g1945__5115 (.A(opcode[3]),
	.B(opcode[0]),
	.Y(n_3));
   NAND2XL g1940__7482 (.A(opcode[0]),
	.B(b),
	.Y(n_13));
   INVXL g1947 (.A(opcode[3]),
	.Y(n_10));
   INVXL g1950 (.A(b),
	.Y(n_21));
   INVXL g1952 (.A(opcode[1]),
	.Y(n_8));
   INVXL g1951 (.A(a),
	.Y(n_4));
   INVXL g1949 (.A(opcode[2]),
	.Y(n_29));
   NAND2BX1 g2 (.AN(opcode[0]),
	.B(opcode[3]),
	.Y(n_79));
   NAND2BX1 g1954 (.AN(n_50),
	.B(en),
	.Y(n_80));
endmodule

